### PR TITLE
changes: minor bug fixes.

### LINKED ISSUE #1: Opening Archipelago Menu During Start Room Selection Resets Floor
While you are selecting the starting room of a new floor, if you open the Archipelago menu, upon return the room flag will be at the Loot stage. Clicking Proceed regenerates the next floor completely, allowing you to keep regenerating until you find a layout/boss that is preferable.

### LINKED ISSUE #2: Game Crash on boss chest
The first time I opened a boss chest, my game immediately crashed. I do not have the logs, but the error was in the core graphics engine. I expect that it had trouble with the first instance of the Archipelago logo in the boss chest, as no other chest has given me trouble since.

### PR DESCRIPTION
**Pull request by BloodySw**
- top bar icon no longer clickable when a room is not completed and between acts
- top bar icon is now greyed out when it's not possible to open it
- number next to top bar icon now shows number of items received since you last opened it (also now shows correct amount instead of 0 when connecting)
- boss relics rewards can now be opened and closed as many times as needed without consuming the reward (until a boss relic is chosen)
- the previous screen will now be closed upon opening the Archipelago reward screen, returning to "null"/battle screen (small bug - the game now softlocks between acts. Band-aid fix by making it impossible to open between acts: on room -1 when act>1)
- boss chest now no longer opens the reward screen. The location is sent upon entering the room anyway. Removing the boss chest reward screen fixes the crash when using controller support (game was trying to place the cursor on the first item in an empty list)

### CODE REVIEW

**Comment by KonoTyran** [comment]
I know this fixes #2 this this affect #1 at all?

**Comment by BloodySw** [comment]
The game seems to have several hardcoded situations where triggering them, changes the room phase to "competed" (thus showing the "proceed" arrow and making it possible to move to the next room). This seems to happen when consuming rare card draw or when obtaining certain relics, such as bottled flame/lighting/tornado. Because the reward screen is now only openable when room is already completed, it should fix the "autocompleting" issue. Also I made it impossible to open menu between acts, so it shouldn't regenerate the act.

File: src/main/java/ArchipelagoMW/patches/TopPanelPatch.java [hunk 1]
```diff
@@ -96,8 +98,12 @@ private static void renderAPIcon(SpriteBatch sb) {
         } else {
             sb.setColor(Color.WHITE);
         }
+        if(AbstractDungeon.getCurrRoom().phase != AbstractRoom.RoomPhase.COMPLETE || (AbstractDungeon.getCurrMapNode().y == -1 && AbstractDungeon.actNum != 1)){
```
Comment (KonoTyran) [inline src/main/java/ArchipelagoMW/patches/TopPanelPatch.java]: this should be above the draw function above and you should just set the color there instead of setting the color and redrawing the icon on top of what was already there.

**Review by KonoTyran — CHANGES_REQUESTED** [review]
If desired, you could also add your name to `src/main/resources/ModTheSpire.json` and `AUTHOR` in `src/main/java/ArchipelagoMW/ArchipelagoMW.java`

**Comment by BloodySw** [comment]
I think I added the change requested?I'm not sure

**Review by KonoTyran — APPROVED** [review]
